name: Bitbake qemu hardknott image
on:
  push:
    branches: [ "master", "hardknott" ] #adjust as needed
  pull_request:
    branches: [ "master", "hardknott" ] #adjust as needed

jobs:
  spawn-build-container:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: setup clean build
        run: |
          mkdir out && cd out
          ./../.github/workflows/setup_hardknott.sh 

      - name: bake
        run: |
          cd out
          source poky/oe-init-build-env
          bitbake core-image-minimal
        shell: bash

    #   - name: run qemu
    #     run: |
    #       cd out
    #       source poky/oe-init-build-env
    #       runqemu qemux86-64 slirp nographic
    #     shell: bash
    
      - uses: actions/upload-artifact@v3
        with:
            name: rootfs-${{ steps.date.outputs.builddate }}-${{ github.sha }}
            path: /mnt/resource/hardknott/tmp/deploy/images/qemux86-64/*.rootfs.tar.bz2

      - run: rm -rf out # clean
